### ISSUE TITLE
adoptium-marketplace-staging-checker broken

### ISSUE THREAD

**Issue by gnu-andrew** [adoptium/marketplace-api.adoptium.net#267]
The automated check just failed when trying to verify the April 2024 marketplace update:

* PR: https://github.com/rh-openjdk/marketplace/pull/44
* Test run: https://github.com/rh-openjdk/marketplace/actions/runs/8757709430/job/24036958248?pr=44

~~~
Error:  Failed to execute goal io.quarkus:quarkus-maven-plugin:3.10.0.CR1:build (default) on project adoptium-marketplace-staging-checker: Execution default of goal io.quarkus:quarkus-maven-plugin:3.10.0.CR1:build failed: An API incompatibility was encountered while executing io.quarkus:quarkus-maven-plugin:3.10.0.CR1:build: java.lang.NoSuchMethodError: 'void io.quarkus.bootstrap.app.JarResult.<init>(java.nio.file.Path, java.nio.file.Path, java.nio.file.Path, java.lang.String, java.lang.String)'
~~~

**Comment by tellison** [comment]
Fixed via https://github.com/adoptium/marketplace-api.adoptium.net/commit/65bfab1c4fbab0cd9f9a04afe077e6e2403d8438

/cc: @johnoliver

**Comment by gnu-andrew** [comment]
I tried a re-run and still get:
~~~
Error:  Failed to execute goal io.quarkus:quarkus-maven-plugin:3.10.0:build (default) on project adoptium-marketplace-staging-checker: Execution default of goal io.quarkus:quarkus-maven-plugin:3.10.0:build failed: An API incompatibility was encountered while executing io.quarkus:quarkus-maven-plugin:3.10.0:build: java.lang.NoSuchMethodError: 'void io.quarkus.bootstrap.app.JarResult.<init>(java.nio.file.Path, java.nio.file.Path, java.nio.file.Path, java.lang.String, java.lang.String)'
~~~
https://github.com/rh-openjdk/marketplace/actions/runs/8757709430/job/24210250466

**Comment by johnoliver** [comment]
@gnu-andrew sorry I didnt notice you commented on this. So I think I have identified the issue. So the build effectively points to the `production` branch of the marketplace-api.  This has an issue where it is trying to use the latest quarkus maven plugin that is incompatible with our code. To fix this we will need to do a merge to the production branch, will have to be next week. If you need a build before then, I did a temporary fix at:

https://github.com/microsoft/openjdk-adoptium-marketplace-data/pull/15/commits/bf50db498d642b68a6365cf2f5542ef68ea87ad1

To effectively re-point the build to not use the production branch

**Comment by johnoliver** [comment]
A release has been done, and it appears to me like tests are now passing. @gnu-andrew feel free to re-open or create a new issue if it still does not work for you

**Comment by gnu-andrew** [comment]
Things went fine with the July updates, so looks good. Thanks for fixing.
